@Quiz3API_HostAddress = http://localhost:5269
@AdminToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImFkbWluIiwicm9sZSI6IkFkbWluIiwibmJmIjoxNzc2OTQ3OTc5LCJleHAiOjE3NzY5NDgyNzksImlhdCI6MTc3Njk0Nzk3OX0.meuznwVUM89qXElPhYpju2NhxuFYHq9G5b7qh3ri4bg
@UserToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InVzZXIiLCJyb2xlIjoiVXNlciIsIm5iZiI6MTc3Njk0Nzk5MSwiZXhwIjoxNzc2OTQ4MjkxLCJpYXQiOjE3NzY5NDc5OTF9.KHtxw-YFRoXNF_O_nEDDH_jECKkwxMf4a662su4Jn5A

###

POST {{Quiz3API_HostAddress}}/api/auth/login
X-API-KEY: MYAPIKEY
Content-Type: application/json

{
  "username": "user",
  "password": "1234"
}

###
GET {{Quiz3API_HostAddress}}/api/tasks
Authorization: Bearer {{AdminToken}}

###

GET {{Quiz3API_HostAddress}}/api/tasks/1
Authorization: Bearer {{UserToken}}

###

POST {{Quiz3API_HostAddress}}/api/tasks
Authorization: Bearer {{UserToken}}
Content-Type: application/json
{
  "title": "New Task 3",
  "isCompleted": true
}

###
PUT {{Quiz3API_HostAddress}}/api/tasks/2
Authorization: Bearer {{AdminToken}}
Content-Type: application/json
{
  "title": "Updated Task 1",
  "isCompleted": true
}

###
DELETE {{Quiz3API_HostAddress}}/api/tasks/1
Authorization: Bearer {{AdminToken}}