@Quiz3API_HostAddress = http://localhost:5269
@AdminToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImFkbWluIiwicm9sZSI6IkFkbWluIiwibmJmIjoxNzc2OTQwODczLCJleHAiOjE3NzY5NDQ0NzMsImlhdCI6MTc3Njk0MDg3M30.LbZLLgedd48jTOhq8tGOxfK_DhsLqwFblbGdw36NOuw
@UserToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Imt1cnQiLCJyb2xlIjoiVXNlciIsIm5iZiI6MTc3Njk0MDg0OCwiZXhwIjoxNzc2OTQ0NDQ4LCJpYXQiOjE3NzY5NDA4NDh9.P0PQprPECV9fg6nllMrijyRd7iruc_bQ5N-3wVCEZiY

###

POST {{Quiz3API_HostAddress}}/api/auth/Login
X-API-KEY: MYAPIKEY
Content-Type: application/json

{
  "username": "kurt",
  "password": "1234"
}

###
GET {{Quiz3API_HostAddress}}/api/tasks
Authorization: Bearer {{AdminToken}}

###

GET {{Quiz3API_HostAddress}}/api/tasks/1
Authorization: Bearer {{AdminToken}}

###

POST {{Quiz3API_HostAddress}}/api/tasks
Authorization: Bearer {{AdminToken}}
Content-Type: application/json
{
  "title": "New Task 2",
  "isCompleted": true
}

###
PUT {{Quiz3API_HostAddress}}/api/tasks/1
Authorization: Bearer {{AdminToken}}
Content-Type: application/json
{
  "title": "Updated Task 1",
  "isCompleted": true
}